version: '3'

services:
  web:
    image: node
    ports:
      - 9090:${PORT}
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./.env/:/app/.env
      - ./package.json:/app/package.json
    command: sh -c "npm install && npm run start" 
